services:
  - type: web
    name: youtube-downloader-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_ORIGIN
        value: https://your-frontend.vercel.app
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health